### ISSUE TITLE
Login Status causes line breaks on example website

### ISSUE THREAD

**Issue by smross** [JoshuaMaiorino/RockTheme-Agency#2]
**Description:**
If the Login Status block is added to a layout, menu items with two words will appear like they have a line break

**Steps to Reproduce:**

1. Assign the theme to the 'example' external site
2. Add the Login Status block to the layout zone. (I have seen this happen with homepage, left sidebar, right sidebar, and full width)
3. The 'New Here' menu link now is two lines

**Expected Behavior:**
Menu items will not line break when the login option appears on the page

**Actual Behavior:**
The 'New Here?' header menu item is now 2 lines, visually looking "off" in comparison to the others

**Comment by smross** [comment]
Addin a page titled `Lorem&nbsp;Ipsum` (with the nonbreaking space) does not have this issue

**Comment by JoshuaMaiorino** [comment]
The issue is that the login block has classes that conflict, and there's only so much space for the header.  So there are two things that can be done here to help.
1) Remove the Login from the Main Nav.
2) Remove an item from the main nav.  I know this isn't ideal, but either renaming a page or removing it from the nav so that it doesn't get overfull.  This theme doesn't have a ton space for the nav. (notice the screenshots,  I removed one of the pages to make the nav smaller.)

I could go back and try to tweak the CSS to better accommodate the login block as well.
